#
# Blog Settings
#
name: huugle
description: 因上努力，果上随缘。
url: http://m.hu6.me
title: 形而上学
subtitle: 因上努力，果上随缘。
gravatar_url: http://ww2.sinaimg.cn/small/51a2bfdagw1ej3zy42zksj20fk0fkgma.jpg
#subscribe_rss: http://feed.feedsky.com/huugle
encoding: utf-8

# Github repositories
github_user: hugohu
github_repo_url: https://github.com/hugohu/hugohu.github.io/

# Twitter
twitter_user: shunhu
twitter_tweet_button: false

# Disqus Comments
#disqus_short_name: huugle
#disqus_show_comment_count: true

# Google Analytics
#google_analytics_tracking_id: UA-49932176-1
#google_analytics_domain: huugle.org

# duoshuo
duoshuo_short_name: shunhu

#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title.html
paginate: 20
paginate_path: "page/:num"
category_dir: categories
